name: "Setup sbt installer"
description: "Sets up sbt runner script"
inputs:
  sbt-runner-version:
    description: "The runner version (The actual version is controlled via project/build.properties)"
    required: true
    default: 1.10.2
runs:
  using: "composite"
  steps:
    - name: Set up cache paths
      id: cache-paths
      shell: bash
      run: |
        echo "setupsbt_path=$HOME/work/_setupsbt" >> $GITHUB_OUTPUT

    - name: Cache sbt distribution
      id: cache-dir
      uses: actions/cache@v4
      with:
        path: ${{ steps.cache-paths.outputs.setupsbt_path }}
        key: ${{ runner.os }}-sbt-${{ inputs.sbt-runner-version }}-1.1.1

    - name: "Install sbt"
      shell: bash
      if: steps.cache-dir.outputs.cache-hit != 'true'
      run: |
        mkdir -p "${{ steps.cache-paths.outputs.setupsbt_path }}"
        curl -sL https://github.com/sbt/sbt/releases/download/v$SBT_RUNNER_VERSION/sbt-$SBT_RUNNER_VERSION.zip > "${{ steps.cache-paths.outputs.setupsbt_path }}/sbt-$SBT_RUNNER_VERSION.zip"
        pushd "${{ steps.cache-paths.outputs.setupsbt_path }}"
        unzip -o "sbt-$SBT_RUNNER_VERSION.zip"
        popd
      env:
        SBT_RUNNER_VERSION: ${{ inputs.sbt-runner-version }}

    - name: "Setup PATH"
      shell: bash
      run: |
        pushd "${{ steps.cache-paths.outputs.setupsbt_path }}"
        ls sbt/bin/sbt
        echo "$PWD/sbt/bin" >> "$GITHUB_PATH"
        popd
